#!/bin/bash

echo "🚀 Todo Calendar Backend - Render Deployment Guide"
echo "=================================================="
echo ""

echo "📋 Prerequisites:"
echo "  ✓ Git repository initialized"
echo "  ✓ GitHub account"
echo "  ✓ Render account (sign up at https://render.com)"
echo ""

echo "🔗 Step 1: Push to GitHub"
echo "----------------------------------------"
echo ""
echo "Run these commands:"
echo ""
echo "  git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
echo "⚠️  Replace YOUR_USERNAME and YOUR_REPO with your GitHub username and repository name"
echo ""

read -p "Have you pushed to GitHub? (y/n): " pushed

if [ "$pushed" != "y" ]; then
    echo ""
    echo "Please push to GitHub first, then run this script again."
    exit 1
fi

echo ""
echo "🌐 Step 2: Deploy on Render"
echo "----------------------------------------"
echo ""
echo "1. Go to: https://dashboard.render.com/select-repo?type=web"
echo ""
echo "2. Connect your GitHub repository: Aditya-Prakash14/task-m"
echo ""
echo "3. Configure your service:"
echo "   - Name: todo-calendar-backend"
echo "   - Environment: Node"
echo "   - Region: Oregon (US West)"
echo "   - Branch: main"
echo "   - Build Command: npm install && npx prisma generate"
echo "   - Start Command: npx prisma migrate deploy && npm start"
echo ""
echo "4. Add Environment Variables:"
echo "   ┌─────────────────┬──────────────────────────────────────────────────┐"
echo "   │ Key             │ Value                                            │"
echo "   ├─────────────────┼──────────────────────────────────────────────────┤"
echo "   │ DATABASE_URL    │ mysql://YLVysNuS5CG8ors.root:KqbqoFfKqOd2Fp7z@gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/test?sslaccept=strict │"
echo "   │ JWT_SECRET      │ 3d267399ddc1df2bae5509a4470058f972a6e2b60bbfca63b424c5d58f2a893a │"
echo "   │ JWT_EXPIRE      │ 7d                                               │"
echo "   │ NODE_ENV        │ production                                       │"
echo "   └─────────────────┴──────────────────────────────────────────────────┘"
echo ""
echo "5. Click 'Create Web Service'"
echo ""
echo "6. Wait for deployment to complete (3-5 minutes)"
echo ""
echo ""
echo "✅ After Deployment"
echo "----------------------------------------"
echo ""
echo "Your API will be available at: https://todo-calendar-backend.onrender.com/api"
echo ""
echo "Test your deployment:"
echo '  curl https://todo-calendar-backend.onrender.com/api/auth/register \\'
echo '    -H "Content-Type: application/json" \\'
echo '    -d '"'"'{"name":"Test User","email":"test@example.com","password":"Test123456"}'"'"
echo ""
echo "Update your Electron app:"
echo "  Edit: electron-app/renderer/js/api.js"
echo "  Change: const API_BASE_URL = 'https://todo-calendar-backend.onrender.com/api';"
echo ""
echo ""
echo "📚 Useful Commands"
echo "----------------------------------------"
echo "  View logs: Check Render dashboard → Logs tab"
echo "  Redeploy: Render dashboard → Manual Deploy → Deploy latest commit"
echo "  Environment variables: Render dashboard → Environment tab"
echo ""
echo "🎉 Happy deploying!"
